apiVersion: apps/v1
kind: Deployment
metadata:
  name: loc-nodejs-deployment-k8s
  namespace: loc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loc-nodejs-deployment-k8s
  template:
    metadata:
      labels:
        app: loc-nodejs-deployment-k8s
    spec:
      containers:
      - name: loc-nodejs-k8s
        image: thanhloc2609/k8s-nodejs
        ports:
        - containerPort: 1313
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: loc-nodejs-service-k8s
  namespace: loc
spec:
  ports:
  - port: 1313
    targetPort: 1313
    protocol: TCP
    name: http
    nodePort : 32667
  selector:
    app: loc-nodejs-deployment-k8s
